name: build_wheel
on: [push]
permissions: read-all
jobs:
  build_wheel:
    strategy:
      matrix:
        python-version:
          - 3.9.20
          - 3.12.6
    runs-on: [self-hosted, libpff]
    steps:
    - uses: actions/checkout@8edcb1bdb4e267140fa742c62e395cd74f332709
    - name: Download test data
      run: |
        if test -x "synctestdata.sh"; then ./synctestdata.sh; fi
    - name: Prepare build
      run: |
        ./synclibs.sh --use-head && ./autogen.sh && ./configure && make sources >/dev/null
    - name: Install Python
      run: |
        uv python install ${{ matrix.python-version }}
    - name: Create virtual environment
      run: |
        rm -rf venv
        uv venv --python ${{ matrix.python-version }} venv
        echo "$(pwd)/venv/bin" >> $GITHUB_PATH
    - name: Install Python dependencies
      run: |
        uv pip install \
          'build' \
          'mypy' \
          'setuptools>=65' \
          'wheel'
    - name: Build libpff-python wheel
      run: |
        python3 -m build --no-isolation --outdir=dist --wheel
        uv pip install --no-index --find-links=dist libpff-python
        python3 tests/runtests.py
    - name: Build pypff-stubs wheel
      working-directory: stubs
      run: |
        python3 -m build --outdir=dist --wheel
        uv pip install --no-index --find-links=dist pypff-stubs
        mypy --strict -c 'import pypff; reveal_type(pypff.file)'
    - name: Upload wheels
      run: |
        ./upload-wheel.sh dist/libpff_python*.whl
        ./upload-wheel.sh stubs/dist/pypff_stubs*.whl
